settings:
  title: 'Ceyase 下属站点状态检查'
  url: 'https://status.ceyase.cn' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系统正常运行'
  notAllmonitorsOperational: '并非所有系统都能正常运行'
  monitorLabelOperational: '运行'
  monitorLabelNotOperational: '未投入运行'
  monitorLabelNoData: '无数据'
  dayInHistogramNoData: '无数据'
  dayInHistogramOperational: '一切顺利'
  dayInHistogramNotOperational: ' 事件' # xx incident(s) recorded

monitors:
  - id: ceyase-cn
    name: ceyase.cn
    description: '天机Ceyase 的个人博客'
    url: 'https://ceyase.cn/'
    followRedirect: true

  - id: ute-ceyase-cn
    name: ute.ceyase.cn
    description: 'Undertale Engine 维基'
    url: 'https://ute.ceyase.cn/'
    followRedirect: true

  - id: utbbs-top
    name: utbbs.top
    description: 'Undertale (传说之下) 中文论坛'
    url: 'https://utbbs.top/'
    followRedirect: true
